app1/urls.py
from django.urls import path

from . import views

app_name = 'app1'


urlpatterns = [
    path('', views.index, name='index'),
    #--------------------------21.07.12 detail, answer url 부여
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    #--------------------------21.07.13 질문등록 url부여---------
    path('question/create/', views.question_create, name='question_create')
]

common/urls.py
from django.urls import path

from . import views

app_name = 'common'

urlpatterns = [
    path('signup/', views.signup, name='signup')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from app1 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/', include('app1.urls')),
    path('common/', include('common.urls')),
]

app1/models.py
from django.db import models

# Create your models here.
# 질문과 답변 테이블 생성(21.7.8 홍성근 작성)
# 질문 테이블 : Question
# 질문 제목 : subject
# 질문 내용 : content
# 질문작성일자 :create_date
# 답변 테이블 : Answer
#----------------------질문테이블-------------------
class Question(models.Model):
    subject = models.CharField(max_length=100)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject

#-----------------------답변테이블------------------
# 답변 테이블 : Answer
# 답변 내용 : answer_content
# 답변 작성일자 : create_date
# 질문 제목 : question(어떤 질문에대한 답변인지를 알아야 하기때문에)
class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_content = models.TextField()
    create_date = models.DateTimeField()

common/models.py
from django.db import models

# Create your models here.

app1/forms.py
from django import forms
from app1.models import Question

# QuestionForm 같은 클래스를 장고 폼이라 부른다.
# 장고 폼에는 2가지 폼이 있고
# 일반 폼, 모델 폼 이라는 것이 있음
class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
#----------210714 질문등록하기, 내용에 부트스트랩 적용
# 왜 html에서 적용하지 않고 모듈에서 적용하는가?
# 이유: 템플릿 태그 {{ form.as_p}} 때문
# { form.as_p}} : 모델(테이블)의 정보를 받아 form과 요소를 자동으로 생성하는 템플릿 태그
# 테이블 컬럼의 숫자에 관계 없이 컬럼을 불러 올수 있다는 장점이 있지만
# html(templete)단 에서 스타일을 적용하기 힘들다 라는 단점이 있음
# 이러한 단점을 widgets 속성을 이용해서 해당 탬플릿(html) 로딩시 클래스 정보를 전달해주는 방식으로 커버한다.
# key값은 해당 컬럼명으로 value값은 적용할 속성으로 쓴다.
        widgets = {
           'subject': forms.TextInput(attrs={'class': 'form-control'}),
           'content': forms.Textarea(attrs={'class': 'form-control', 'rows':10}),
        }

        labels = {
            'subject': '제목',
            'content': '내용',
        }

app1/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
# views.py의 위치에서 models.py를 찾아서 question을 import 하라는 의미
from .models import Question
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from app1.forms import QuestionForm
#21.07.19 페이징 처리 관련 모듈 import
from django.core.paginator import Paginator



def index(request):
    #request: 외부 사용자의 요청을 받아오는 것
    #render : 템플릿을 로딩할 때 사용
    #redirect: URL로 이동시 사용
    #사용자가 localhost:8000/app1 페이지 접속이라는 요청을 보냈다.
    #view -> urls에 어떤함수를 실행해야 하는지 확인한다.
    #21.07.09 질문 목록 가져오기.
    # view에서 model단에 요청
    # 요청의 내용: 조회(Question 테이블(모델) create_date 컬럼을 기준으로 정렬해서 가져옴 -> 그 걸과를 question_list에 저장

    page = request.GET.get('page', '1')

    question_list = Question.objects.order_by('-create_date')
    # context라는 변수에 딕셔너리 형태로 question_list key와 value를 저장
    # 템플릿단에서 해당 데이터를 쉽게 조회하기 위해

    # 페이징 처리내용
    # 가져온 데이터를 10개씩 보여주라.

    paginator = Paginator(question_list, 10)
    page_obj= paginator.get_page(page)

    context = {'question_list': page_obj}
    # 받은 요청에 대해 (request)
    # app1/question_list.html 탬플릿을 열어주고
    # 해당 탬플릿에 context 값을 전송
    return render(request, 'app1/question_list.html', context)

def detail(request, question_id):
    #get_object_or_404: 기본키에 해당하는 건이 없다면 404페이지 출력
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'app1/question_detail.html', context)
# 질문등록함수 21.07.13
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    question.answer_set.create(answer_content=request.POST.get('answer_content'), create_date=timezone.now())
    return redirect('app1:detail', question_id=question.id)

def question_create(request):
    # 수정 내용 : GET, POST 방식에 대한 처리
    # question_form으로 들어올때
    # 질문을 등록할때
    # POST 방식인지 GET 방식인지 확인
    # 이유: 단순히 질문등록 페이지를 오픈한 것인지
    # 아니면 질문등록 페이지에 데이터를 입력해서 저장한 것인지를 구분
    if request.method == "POST":
        # forms.py에 설정한 QuestionForm 클래스를 호출
        # request.post: 사용자가 입력한 데이터를 받아와 준다.
        form = QuestionForm(request.POST)
        # 폼에 들어온 값이 올바른 값(정상적인 값)인지를 확인
        if form.is_valid():
            # 저장을 하기 전 잠시 유보.
            # question 변수에 form에서 받아온 데이터는 넣어 두었지만
            # 아직 DB로 저장하지는 않았다.
            question = form.save(commit=False)
            # create_date 컬럼을 따로 입력받지 않은 이유?
            # 질문등록의 날짜 시간의 경우 현재 시간으로 입력받기 위해
            # view에서 처리
            question.create_date = timezone.now()
            question.save()
            return redirect('app1:index')
    else:
        form = QuestionForm()
    return render(request, 'app1/question_form.html', {'form': form})
    # context = {'form': form}
    # return render(request, 'app1/question_form.html', context)와 같다.

#0714수정 (기존내용 백업)
# def question_create(request):
#     form = QuestionForm()
#     return render(request, 'app1/question_form.html', {'form': form})

# get 방식 post방식(데이터 전송방식)
# 1. get방식: url에 파라미터를 붙여서 전송하는 방식
#             속도가 빠르다는 장점이 있지만
#             url에 데이터를 실어서 보내기 때문에 보안에 취약하거나
#             그 외 데이터 전송에 여러가지 제한 사항이 있다.
# 2. 포스트 방식 : HTML의 BODY영역에 데이터를 실어 보내는 방식(form)
#                대용량의 데이터를 보낼 수 있고 주소에 실어 보내지 않기 때문에
#                get방식에 비해 보안성 또한 좋다.

# csrf_token: 브라우저에서 작성된 데이터가 올바른 데이터 인지,
#             혹은 진짜 웹 브라우저에서 작성된 데이터인지 판단하는 기능

# <!--템플릿 태그-->
# <!--{% if 요청 받은 값(question_list)%} : question_list가 있을경우-->
# <!--{% for 임시변수 in 요청받은값(딕셔너리 키값) %} : 딕셔너리의 키의 value를-->
# <!--반복하여 순차적으로 임시변수에 대입.-->
# <!--{{ 임시변수.컬럼 }} : for문에 의해 선언된 임시변수의 컬럼출력-->

#
# {{ }} : 데이터와 관련된 내용을 출력할 때 사용되는 탬플릿 태그
# {% %} : 탬플릿 태그의 속성, 문법등을 사용할때 쓰는 태그

common/views.py
from django.shortcuts import render


# Create your views here.
def signup():
    return None

templates/app1/question_detail.html
{% extends 'base.html'%}
{% block content %}

<div class="container my-3">
    <h2 class="border-bottom py-2">{{question.subject}}</h2>
    <div class="card my-3">
        <div class="body">
            <div class="card-text" style="white-space: pre-line">
                {{question.content}}
            </div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{question.create_date}}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}
        개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all%}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line">
                {{answer.answer_content}}
            </div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div><!-- card my-3 end-->
    {% endfor %}
<form action="{% url 'app1:answer_create' question.id %}" method="post">
{% csrf_token %}
<textarea name="answer_content" id="answer_content" rows="15"></textarea>
<input type="submit" value="답변등록하기">
</form>
</div>
{% endblock %}

templates/app1/question_detail_bak0713.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<h1>{{question.subject}}</h1>
<p>{{question.content}}</p>

<h5>{{ question.answer_set.count}}개의 답변이 있습니다.</h5>
<div>
    <ul>
        {% for answer in question.answer_set.all %}
        <li>{{ answer.answer_content }}</li>
        {% endfor %}
    </ul>

</div>

<form action="{% url 'app1:answer_create' question.id %}" method="post">
{% csrf_token %}
<textarea name="answer_content" id="answer_content" rows="15"></textarea>
<input type="submit" value="답변등록하기">
</form>
</body>
</html>

templates/app1/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" CLASS="post-form my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <div class="form-group">
            <!--label: input태그와 연계해서 사용되는 태그
                       input태그를 제어해서 상태를 변경하게 도와주는 태그
                for: 다른태그와 결합할때 사용하는 속성
                       결합하고자 하는 태그의 아이디 값과 같아야 한다-->
            <label for="subject">제목</label>
            <!-- form.컬럼명.value : 오류, 혹은 잘못된 연결등 예기치 못한 상황이나 사용자의 입력 실수가 있었을때 해당 요소에 값이
                                    있었다면 그 값의 초기화를 방지해 주는 탬플릿 태그 문법
                 default_if_none: 기본 값을 설정하는 문법 -->
            <input type="text" class="form-control" id ="subject" name="subject"
             value="{{form.subject.value|default_if_none:'' }}">

        </div>
        <div>
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">
                {{ form.content.value|default_if_none:'' }}
            </textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장</button>
    </form>
</div>

{% endblock %}

<!--
form: 입력된 데이터를 전송하기 위한 태그

1. 폼이 있는 페이지 접속
2. 폼에 내용을 입력
3. 저장(전송/ 속성: submit)버튼을 눌렀을때 폼 안쪽의 모든 데이터를 서버(로컬 서버)로 전송.
4. Django에서는 받은 폼 데이터를 처리하기 위해 forms.py로 넘겨줌
    (서버는 받은 폼 데이터를 처리하기 위해 웹 프로그램으로 넘겨준다.)
5. forms.py에서 데이터를 받은 후 views.py로 넘겨줌
6. views.py에서 데이터를 처리
7. 처리 결과에 따라 페이지를 웹서버에 전송
8. 로컬 서버는 받은 페이지를 브라우저에 전송
9. 브라우저는 받은 페이지를 보여줌

폼 태그 속성
action: 폼을 전송할 서버 스크립트(템플릿)파일을 지정
name : 폼을 식별하기 위한 이름
target : action에서 지정한 스크립트 파일을 현재 창이 아니라 다른 위치에 열도록 지정하는 속성
method : 폼을 서버에 전송할 http 메서드를 정하는 방법 (GET or POST)
-->

templates/app1/question_form_bak_0714.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" CLASS="post-form my-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">저장</button>

    </form>
</div>

{% endblock%}

templates/app1/question_list.html
{% extends 'base.html'%}
{% load filter %}
{% block content %}
<div class="container my-3">
<!--
   페이징: 컴퓨터가 데이터를 저장하고 검색하는 메모리 관리 기법
   paginator.count : 전체 게시물 갯수를 가져옴
   start_index : 현재 페이지의 시작 인덱스
   end_index: 현재 페이지의 끝 인덱스
   일련번호 = 전체 게시물 개수 - 시작인덱스 - 현재 인덱스 +1
   -->
    <table class="table">
    <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일</th>
        </tr>
    </thead>
    <tbody>
     {% if question_list %}
     {% for question in question_list%}
     <tr>
         <td>{{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1}}</td>
         <td>
             <a href="{% url 'app1:detail' question.id %}">{{question.subject}}
             {% if question.answer_set.count > 0 %}
             <span class="text-danger small m-2">{{question.answer_set.count}}</span>
             {% endif %}</a>
         </td>
         <td>{{ question.create_date}}</td>
     </tr>
     {% endfor%}
     {% else %}
    <tr>
        <td colspan="3">질문이 없습니다.</td>
    </tr>
    {% endif %}
    </tbody>
    </table>
    <!-- 페이징 처리 view 영역 -->
    <ul class="pagination justify-content-center">
        <!-- has previous: 이전 페이지가 있는지 유무를 확인 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <!-- previous_page_number: 이전 페이지 번호 -->
            <a class="page-link" href="?page={{question_list.previous_page_number}}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" aria-disabled="true" tabindex="-1"></a>
        </li>
        {% endif %}
        <!-- 페이지 리스트 출력하기  -->
        <!-- page_range: 페이지의 범위
             number: 현재 페이지 번호 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-2 and page_number <= question_list.number|add:2 %}
            {% if page_number == question_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{page_number}}">{{page_number}}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{page_number}}">{{page_number}}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- has next: 다음 페이지가 있는지 유무를 확인 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <!-- next_page_number: 다음 페이지 번호 -->
            <a class="page-link" href="?page={{question_list.next_page_number}}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" aria-disabled="true" tabindex="-1"></a>
        </li>
        {% endif %}
    </ul>



     <a href="{% url 'app1:question_create'%}" class="btn btn-primary">질문 등록하기</a>

</div>
{% endblock %}

templates/app1/question_list_bak0713.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
{% if question_list %}
    <ul>
        {% for question in question_list %}
            <li><a href="{% url 'app1:detail' question.id %}">{{question.subject}}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>게시글이 없습니다.</p>
{% endif %}

</body>
</html>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <title>ㅋㅋㅋㅋㅋ</title>
</head>
<body>
<!--navbar 추가 21.07.16-->
{% include 'navbar.html' %}
{% block content %}
{% endblock%}

</body>
</html>

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>계정생성</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary border-bottom">
    <a class="navbar-brand" href="{% url 'app1:index' %}">프로젝트</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="#">로그인</a>
            </li>
        </ul>
    </div>
</nav>